public class MultipleCatchDemo {
    public static void main(String[] args) {
        int[] array = {1, 2, 3, 4, 5};
        try {
            int index = 10;
            int element = array[index];
            System.out.println("Element at index " + index + ": " + element);
            int a = 10;
            int b = 0;
            int result = a / b;
            System.out.println("Result of division: " + result);

        } catch (ArrayIndexOutOfBoundsException e) 
        {
            System.out.println("ArrayIndexOutOfBoundsException: " + e.getMessage());
        } catch (ArithmeticException e) {
            System.out.println("ArithmeticException: " + e.getMessage());
        } finally
        {
            System.out.println("Finally block executed.");
        }
        System.out.println("Program continues after exception handling.");
    }
}